!!omap
- model: !!omap 
  - config_file: ./PoseDiffExps/posediff/configs/default.yaml
  - manip_file: ./config/panda.yaml
  - arch_file: ./config/dream_resnet_f.yaml

- training: !!omap 
  - hyperparameters: !!omap 
    - batch_size: 2
    - epochs: 25
    - lr: 0.0001
    - num_workers: 1
    - optimizer: adam # Choose from [adam, sgd]
  - augment: False # True yet to be implemented

- dataset: !!omap 
  - dataset_path: ./data # WRT root of dataset
  - dataset_type: real # Choose from [real, synth]
  - train_split: 0.8 # The remaining will be used for validation
  - real: !!omap 
    - cam: 3cam_realsense # Choose from [3cam_azure, 3cam_kinect36, 3cam_reaalsense, orb]
  - synth: !!omap 
    - type: train_dr # Choose from [train_dr, test_photo, test_dr]
  - optical_flow_path: ./data_flow 

- logging: !!omap 
  - verbose: False
  - save_results: True
  - output_dir: ./output
